<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/sms.proto

namespace App\Grpc\Sms;

use UnexpectedValueException;

/**
 * 定义枚举变量, 必须从0开始
 *
 * Protobuf type <code>app.grpc.sms.ItemType</code>
 */
class ItemType
{
    /**
     * Generated from protobuf enum <code>Int32Type = 0;</code>
     */
    const Int32Type = 0;
    /**
     * Generated from protobuf enum <code>StrType = 1;</code>
     */
    const StrType = 1;
    /**
     * Generated from protobuf enum <code>FloatType = 2;</code>
     */
    const FloatType = 2;

    private static $valueToName = [
        self::Int32Type => 'Int32Type',
        self::StrType => 'StrType',
        self::FloatType => 'FloatType',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

