// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sms.proto

package sms

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 定义枚举变量, 必须从0开始
type ItemType int32

const (
	ItemType_Int32Type ItemType = 0
	ItemType_StrType   ItemType = 1
	ItemType_FloatType ItemType = 2
)

var ItemType_name = map[int32]string{
	0: "Int32Type",
	1: "StrType",
	2: "FloatType",
}

var ItemType_value = map[string]int32{
	"Int32Type": 0,
	"StrType":   1,
	"FloatType": 2,
}

func (x ItemType) String() string {
	return proto.EnumName(ItemType_name, int32(x))
}

func (ItemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c8d8bdc537111860, []int{0}
}

type SendRequest struct {
	Id                   int64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 map[string]*any.Any `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8d8bdc537111860, []int{0}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SendRequest) GetData() map[string]*any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type SendReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendReply) Reset()         { *m = SendReply{} }
func (m *SendReply) String() string { return proto.CompactTextString(m) }
func (*SendReply) ProtoMessage()    {}
func (*SendReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8d8bdc537111860, []int{1}
}

func (m *SendReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendReply.Unmarshal(m, b)
}
func (m *SendReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendReply.Marshal(b, m, deterministic)
}
func (m *SendReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendReply.Merge(m, src)
}
func (m *SendReply) XXX_Size() int {
	return xxx_messageInfo_SendReply.Size(m)
}
func (m *SendReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendReply proto.InternalMessageInfo

func (m *SendReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type HelloWorldItem struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 ItemType `protobuf:"varint,3,opt,name=type,proto3,enum=sms.ItemType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldItem) Reset()         { *m = HelloWorldItem{} }
func (m *HelloWorldItem) String() string { return proto.CompactTextString(m) }
func (*HelloWorldItem) ProtoMessage()    {}
func (*HelloWorldItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8d8bdc537111860, []int{2}
}

func (m *HelloWorldItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldItem.Unmarshal(m, b)
}
func (m *HelloWorldItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldItem.Marshal(b, m, deterministic)
}
func (m *HelloWorldItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldItem.Merge(m, src)
}
func (m *HelloWorldItem) XXX_Size() int {
	return xxx_messageInfo_HelloWorldItem.Size(m)
}
func (m *HelloWorldItem) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldItem.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldItem proto.InternalMessageInfo

func (m *HelloWorldItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HelloWorldItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloWorldItem) GetType() ItemType {
	if m != nil {
		return m.Type
	}
	return ItemType_Int32Type
}

type HelloWorldRequest struct {
	Data                 map[string]string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Items                []*HelloWorldItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HelloWorldRequest) Reset()         { *m = HelloWorldRequest{} }
func (m *HelloWorldRequest) String() string { return proto.CompactTextString(m) }
func (*HelloWorldRequest) ProtoMessage()    {}
func (*HelloWorldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8d8bdc537111860, []int{3}
}

func (m *HelloWorldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldRequest.Unmarshal(m, b)
}
func (m *HelloWorldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldRequest.Marshal(b, m, deterministic)
}
func (m *HelloWorldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldRequest.Merge(m, src)
}
func (m *HelloWorldRequest) XXX_Size() int {
	return xxx_messageInfo_HelloWorldRequest.Size(m)
}
func (m *HelloWorldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldRequest proto.InternalMessageInfo

func (m *HelloWorldRequest) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *HelloWorldRequest) GetItems() []*HelloWorldItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type HelloWorldReply struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldReply) Reset()         { *m = HelloWorldReply{} }
func (m *HelloWorldReply) String() string { return proto.CompactTextString(m) }
func (*HelloWorldReply) ProtoMessage()    {}
func (*HelloWorldReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8d8bdc537111860, []int{4}
}

func (m *HelloWorldReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldReply.Unmarshal(m, b)
}
func (m *HelloWorldReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldReply.Marshal(b, m, deterministic)
}
func (m *HelloWorldReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldReply.Merge(m, src)
}
func (m *HelloWorldReply) XXX_Size() int {
	return xxx_messageInfo_HelloWorldReply.Size(m)
}
func (m *HelloWorldReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldReply proto.InternalMessageInfo

func (m *HelloWorldReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("sms.ItemType", ItemType_name, ItemType_value)
	proto.RegisterType((*SendRequest)(nil), "sms.SendRequest")
	proto.RegisterMapType((map[string]*any.Any)(nil), "sms.SendRequest.DataEntry")
	proto.RegisterType((*SendReply)(nil), "sms.SendReply")
	proto.RegisterType((*HelloWorldItem)(nil), "sms.HelloWorldItem")
	proto.RegisterType((*HelloWorldRequest)(nil), "sms.HelloWorldRequest")
	proto.RegisterMapType((map[string]string)(nil), "sms.HelloWorldRequest.DataEntry")
	proto.RegisterType((*HelloWorldReply)(nil), "sms.HelloWorldReply")
}

func init() { proto.RegisterFile("sms.proto", fileDescriptor_c8d8bdc537111860) }

var fileDescriptor_c8d8bdc537111860 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0xef, 0x93, 0x30,
	0x18, 0xc7, 0x2d, 0x30, 0x95, 0x87, 0xfc, 0x70, 0xd6, 0xc5, 0x20, 0x89, 0x09, 0xe2, 0x05, 0x77,
	0x60, 0x09, 0xd3, 0x68, 0x76, 0x33, 0x51, 0xe3, 0x0e, 0x5e, 0x8a, 0xc9, 0xce, 0x9d, 0x54, 0x42,
	0x6c, 0x01, 0x69, 0xb7, 0x84, 0xf7, 0xe2, 0x5b, 0xf0, 0x3d, 0x9a, 0x96, 0xe1, 0xc8, 0xb6, 0xfc,
	0x6e, 0x7d, 0xfe, 0x7d, 0x9f, 0x6f, 0x3f, 0x2d, 0xb8, 0x52, 0xc8, 0xb4, 0xed, 0x1a, 0xd5, 0x60,
	0x5b, 0x0a, 0x19, 0xbe, 0x28, 0x9b, 0xa6, 0xe4, 0x6c, 0x65, 0x52, 0xfb, 0xc3, 0xcf, 0x15, 0xad,
	0xfb, 0xa1, 0x1e, 0xff, 0x41, 0xe0, 0xe5, 0xac, 0x2e, 0x08, 0xfb, 0x7d, 0x60, 0x52, 0x61, 0x1f,
	0xac, 0xaa, 0x08, 0x50, 0x84, 0x12, 0x9b, 0x58, 0x55, 0x81, 0x53, 0x70, 0x0a, 0xaa, 0x68, 0x60,
	0x45, 0x76, 0xe2, 0x65, 0x61, 0xaa, 0x95, 0x27, 0xfd, 0xe9, 0x27, 0xaa, 0xe8, 0xe7, 0x5a, 0x75,
	0x3d, 0x31, 0x7d, 0xe1, 0x37, 0x70, 0xff, 0xa7, 0xf0, 0x1c, 0xec, 0x5f, 0xac, 0x37, 0x6a, 0x2e,
	0xd1, 0x47, 0xbc, 0x84, 0xd9, 0x91, 0xf2, 0x03, 0x0b, 0xac, 0x08, 0x25, 0x5e, 0xb6, 0x48, 0x07,
	0x67, 0xe9, 0xe8, 0x2c, 0xfd, 0x58, 0xf7, 0x64, 0x68, 0xd9, 0x58, 0x1f, 0x50, 0xfc, 0x12, 0xdc,
	0x61, 0x5b, 0xcb, 0x8d, 0x9c, 0x90, 0xe5, 0x28, 0x27, 0x64, 0x19, 0xef, 0xc0, 0xff, 0xca, 0x38,
	0x6f, 0x76, 0x4d, 0xc7, 0x8b, 0xad, 0x62, 0x62, 0xe2, 0x7f, 0x66, 0xfc, 0x63, 0x70, 0x6a, 0x2a,
	0x86, 0x7d, 0x2e, 0x31, 0x67, 0xfc, 0x0a, 0x1c, 0xd5, 0xb7, 0x2c, 0xb0, 0x23, 0x94, 0xf8, 0xd9,
	0x9d, 0xb9, 0x93, 0x1e, 0xfe, 0xde, 0xb7, 0x8c, 0x98, 0x52, 0xfc, 0x17, 0xc1, 0xd3, 0xb3, 0xf2,
	0x08, 0xe7, 0xed, 0x09, 0x06, 0x32, 0x30, 0x22, 0x33, 0x78, 0xd5, 0x75, 0x89, 0x04, 0xbf, 0x81,
	0x59, 0xa5, 0x98, 0x90, 0x27, 0x86, 0xcf, 0x2e, 0xc6, 0xf4, 0x66, 0x32, 0x74, 0x84, 0xef, 0xef,
	0xa7, 0xb7, 0x98, 0xd2, 0x73, 0xa7, 0x9c, 0x5e, 0xc3, 0x93, 0xa9, 0x91, 0x9b, 0xb4, 0x96, 0xef,
	0xe0, 0xf1, 0x78, 0x4d, 0x7c, 0x07, 0xee, 0xb6, 0x56, 0xeb, 0x4c, 0x07, 0xf3, 0x07, 0xd8, 0x83,
	0x47, 0xb9, 0xea, 0x4c, 0x80, 0x74, 0xed, 0x0b, 0x6f, 0xa8, 0x32, 0xa1, 0x95, 0x75, 0x00, 0xb9,
	0x90, 0x39, 0xeb, 0x8e, 0xd5, 0x0f, 0x86, 0x13, 0x70, 0xf4, 0x8b, 0xe0, 0xf9, 0xe5, 0x57, 0x08,
	0xfd, 0x49, 0x46, 0x1b, 0xd8, 0x00, 0x9c, 0x3d, 0xe1, 0xe7, 0xb7, 0x69, 0x85, 0x8b, 0xab, 0x7c,
	0xcb, 0xfb, 0xfd, 0x43, 0xf3, 0x21, 0xd6, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x15, 0x9d,
	0x05, 0xca, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SmsServiceClient is the client API for SmsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SmsServiceClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendReply, error)
	HelloWorld(ctx context.Context, in *HelloWorldRequest, opts ...grpc.CallOption) (*HelloWorldReply, error)
}

type smsServiceClient struct {
	cc *grpc.ClientConn
}

func NewSmsServiceClient(cc *grpc.ClientConn) SmsServiceClient {
	return &smsServiceClient{cc}
}

func (c *smsServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendReply, error) {
	out := new(SendReply)
	err := c.cc.Invoke(ctx, "/sms.SmsService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsServiceClient) HelloWorld(ctx context.Context, in *HelloWorldRequest, opts ...grpc.CallOption) (*HelloWorldReply, error) {
	out := new(HelloWorldReply)
	err := c.cc.Invoke(ctx, "/sms.SmsService/HelloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmsServiceServer is the server API for SmsService service.
type SmsServiceServer interface {
	Send(context.Context, *SendRequest) (*SendReply, error)
	HelloWorld(context.Context, *HelloWorldRequest) (*HelloWorldReply, error)
}

// UnimplementedSmsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSmsServiceServer struct {
}

func (*UnimplementedSmsServiceServer) Send(ctx context.Context, req *SendRequest) (*SendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedSmsServiceServer) HelloWorld(ctx context.Context, req *HelloWorldRequest) (*HelloWorldReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloWorld not implemented")
}

func RegisterSmsServiceServer(s *grpc.Server, srv SmsServiceServer) {
	s.RegisterService(&_SmsService_serviceDesc, srv)
}

func _SmsService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sms.SmsService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServiceServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsService_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloWorldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServiceServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sms.SmsService/HelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServiceServer).HelloWorld(ctx, req.(*HelloWorldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SmsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sms.SmsService",
	HandlerType: (*SmsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _SmsService_Send_Handler,
		},
		{
			MethodName: "HelloWorld",
			Handler:    _SmsService_HelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sms.proto",
}
