// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

// 定义一个包名

package proto_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 定义一个请求结构体, 推荐命名法： 方法名+Request
type GetInfoRequest struct {
	// @inject_tag: binding:"required"
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

func (m *GetInfoRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// 定义一个响应结构体, 推荐命名法： 方法名+Response
type GetInfoResponse struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Like                 string   `protobuf:"bytes,3,opt,name=like,proto3" json:"like,omitempty"`
	Sex                  string   `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetInfoResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *GetInfoResponse) GetLike() string {
	if m != nil {
		return m.Like
	}
	return ""
}

func (m *GetInfoResponse) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func init() {
	proto.RegisterType((*GetInfoRequest)(nil), "proto.user.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "proto.user.GetInfoResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x53, 0x7a, 0x20, 0x11, 0x25, 0x4d, 0x2e,
	0x3e, 0xf7, 0xd4, 0x12, 0xcf, 0xbc, 0xb4, 0xfc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21,
	0x71, 0x2e, 0x76, 0x90, 0x4c, 0x7c, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x1b,
	0x88, 0xeb, 0x99, 0xa2, 0x94, 0xc6, 0xc5, 0x0f, 0x57, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a,
	0x24, 0xcd, 0xc5, 0x09, 0x56, 0x9b, 0x97, 0x98, 0x9b, 0x0a, 0x56, 0xcd, 0x19, 0xc4, 0x01, 0x12,
	0xf0, 0x4b, 0xcc, 0x4d, 0x15, 0x12, 0xe0, 0x62, 0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x02, 0x1b, 0x02,
	0x62, 0x0a, 0x09, 0x71, 0xb1, 0xe4, 0x64, 0x66, 0xa7, 0x4a, 0x30, 0x83, 0x55, 0x82, 0xd9, 0x20,
	0x55, 0xc5, 0xa9, 0x15, 0x12, 0x2c, 0x60, 0x21, 0x10, 0xd3, 0x28, 0x98, 0x8b, 0x3b, 0xb4, 0x38,
	0xb5, 0x28, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x85, 0x8b, 0x1d, 0x6a, 0xad, 0x90,
	0x94, 0x1e, 0xc2, 0xe5, 0x7a, 0xa8, 0xce, 0x96, 0x92, 0xc6, 0x2a, 0x07, 0x71, 0xa7, 0x12, 0x43,
	0x12, 0x1b, 0x58, 0xd6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x21, 0xfe, 0x49, 0x08, 0x01,
	0x00, 0x00,
}
